version: '3.4'

services:
  communitymodelapi:
    image: communitymodelapi
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 server-loader\prototype-clustering\api_server\api_server.py "]
    ports:
      - 5678:5678
